language: vi

pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: True
  intent_split_symbol: "+"
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: custom_components.bpemb_featurizer.BytePairFeaturizer
  lang: vi
  vs: 1000
  dim: 25
- name: DIETClassifier
  epochs: 100
  number_of_transformer_layers: 4
  transformer_size: 256
  use_masked_language_model: true
  drop_rate: 0.25
  constrain_similarities: true
  embedding_dimension: 30
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1